const storageKey = 'pulse-setlist-v2';
const demoSongs = [{ title: 'Warm-up', bpm: 100, beats: 4, notes: '' }, { title: 'City Lights', bpm: 116, beats: 4, notes: 'Count in after guitar cue' }, { title: 'Slow Burn', bpm: 72, beats: 3, notes: '' }];
const initial = { settings: { sound: true, flash: true }, setlists: [{ name: 'Tonight', songs: demoSongs }], currentList: 0, current: 0 };
let state = load(), isPlaying = false, beat = 0, timer = null, audio = null, editing = null;
const $ = id => document.getElementById(id);
const list = () => state.setlists[state.currentList];
const song = () => list().songs[state.current];
function load() { try { return JSON.parse(localStorage.getItem(storageKey)) || structuredClone(initial); } catch { return structuredClone(initial); } }
function save() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function render() {
  const s = song();
  $('songName').textContent = s.title; $('songDetails').textContent = `${s.beats} / ${s.beats === 6 ? 8 : 4} · ${s.bpm} BPM`;
  $('bpm').value = s.bpm; $('bpmDisplay').value = s.bpm; $('soundSetting').checked = state.settings.sound; $('flashSetting').checked = state.settings.flash;
  $('setlistTitle').textContent = list().name; $('setlistPicker').replaceChildren(...state.setlists.map((entry, index) => { const option = new Option(entry.name, index, index === state.currentList, index === state.currentList); return option; }));
  $('play').setAttribute('aria-pressed', String(isPlaying)); $('playLabel').textContent = isPlaying ? 'Stop' : 'Start'; $('playIcon').textContent = isPlaying ? '■' : '▶'; $('beatText').textContent = isPlaying ? `Beat ${beat + 1} of ${s.beats}` : 'Ready';
  $('beatRow').replaceChildren(...Array.from({ length: s.beats }, (_, i) => { const dot = document.createElement('span'); dot.className = `beat${i === 0 ? ' accent' : ''}${isPlaying && i === beat ? ' active' : ''}`; return dot; }));
  $('setlist').replaceChildren(...list().songs.map((item, index) => { const row = document.createElement('li'), button = document.createElement('button'); button.type = 'button'; button.className = `song${index === state.current ? ' active' : ''}`; button.innerHTML = '<span class="song-number"></span><span><span class="song-title"></span><span class="song-meta"></span><span class="song-notes"></span></span><span class="song-bpm"></span>'; button.querySelector('.song-number').textContent = index + 1; button.querySelector('.song-title').textContent = item.title; button.querySelector('.song-meta').textContent = `${item.beats} / ${item.beats === 6 ? 8 : 4}`; button.querySelector('.song-notes').textContent = item.notes || ''; button.querySelector('.song-bpm').textContent = item.bpm; button.addEventListener('click', () => { state.current = index; beat = 0; stop(); save(); render(); }); row.append(button); return row; }));
}
function playClick(accent) { if (!state.settings.sound) return; audio ||= new (window.AudioContext || window.webkitAudioContext)(); const osc = audio.createOscillator(), gain = audio.createGain(); osc.frequency.value = accent ? 1100 : 760; gain.gain.setValueAtTime(.12, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .075); osc.connect(gain).connect(audio.destination); osc.start(); osc.stop(audio.currentTime + .08); }
function flash(accent) { if (!state.settings.flash) return; const el = $('flash'); el.className = `flash ${accent ? 'accent' : 'hit'}`; setTimeout(() => el.className = 'flash', 160); }
function tick() { const accent = beat === 0; playClick(accent); flash(accent); render(); beat = (beat + 1) % song().beats; timer = setTimeout(tick, 60000 / song().bpm); }
function start() { if (!isPlaying) { isPlaying = true; beat = 0; tick(); render(); } }
function stop() { isPlaying = false; clearTimeout(timer); timer = null; render(); }
function openSong(index) { editing = index; const s = index === null ? { title: '', bpm: 120, beats: 4, notes: '' } : list().songs[index]; $('dialogTitle').textContent = index === null ? 'Add song' : 'Edit song'; $('titleInput').value = s.title; $('tempoInput').value = s.bpm; $('signatureInput').value = s.beats; $('notesInput').value = s.notes; $('deleteSong').hidden = index === null; $('songDialog').showModal(); }
$('play').addEventListener('click', () => isPlaying ? stop() : start());
$('slower').addEventListener('click', () => { song().bpm = Math.max(40, song().bpm - 1); save(); render(); }); $('faster').addEventListener('click', () => { song().bpm = Math.min(240, song().bpm + 1); save(); render(); }); $('bpm').addEventListener('input', e => { song().bpm = Number(e.target.value); save(); render(); });
$('addSong').addEventListener('click', () => openSong(null)); $('newSetlist').addEventListener('click', () => { const name = prompt('Name this set list', 'New set list'); if (!name?.trim()) return; state.setlists.push({ name: name.trim(), songs: [{ title: 'New song', bpm: 120, beats: 4, notes: '' }] }); state.currentList = state.setlists.length - 1; state.current = 0; beat = 0; save(); render(); }); $('renameSetlist').addEventListener('click', () => { const name = prompt('Rename set list', list().name); if (name?.trim()) { list().name = name.trim(); save(); render(); } }); $('setlistPicker').addEventListener('change', e => { state.currentList = Number(e.target.value); state.current = 0; beat = 0; stop(); save(); render(); });
$('settingsButton').addEventListener('click', () => $('settingsDialog').showModal()); $('soundSetting').addEventListener('change', e => { state.settings.sound = e.target.checked; save(); }); $('flashSetting').addEventListener('change', e => { state.settings.flash = e.target.checked; save(); });
$('songForm').addEventListener('submit', e => { if (e.submitter?.value !== 'default') return; const item = { title: $('titleInput').value.trim(), bpm: Number($('tempoInput').value), beats: Number($('signatureInput').value), notes: $('notesInput').value.trim() }; if (!item.title) { e.preventDefault(); return; } if (editing === null) { list().songs.push(item); state.current = list().songs.length - 1; } else list().songs[editing] = item; beat = 0; save(); render(); }); $('deleteSong').addEventListener('click', () => { if (list().songs.length === 1) return; list().songs.splice(editing, 1); state.current = Math.min(state.current, list().songs.length - 1); $('songDialog').close(); save(); render(); });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js'); render();
