const storageKey = 'pulse-setlist-v3';
const demoSongs = [{ title: 'Warm-up', bpm: 100, beats: 4, notes: '' }, { title: 'City Lights', bpm: 116, beats: 4, notes: 'Count in after guitar cue' }, { title: 'Slow Burn', bpm: 72, beats: 3, notes: '' }];
const initial = { settings: { sound: true, flash: true, soundType: 'wood', theme: 'blue', font: 'normal' }, setlists: [{ name: 'Tonight', color: '#8eaeff', songs: demoSongs }], master: demoSongs, currentList: 0, current: 0 };
let state = load(), isPlaying = false, beat = 0, timer = null, audio = null, editing = null;
const $ = id => document.getElementById(id); const list = () => state.setlists[state.currentList]; const song = () => list().songs[state.current]; const copy = item => JSON.parse(JSON.stringify(item));
function load() { try { const data = JSON.parse(localStorage.getItem(storageKey)) || JSON.parse(localStorage.getItem('pulse-setlist-v2')); if (!data) return copy(initial); data.settings = { ...initial.settings, ...(data.settings || {}) }; data.master ||= data.setlists.flatMap(x => x.songs); data.setlists.forEach(x => x.color ||= '#8eaeff'); return data; } catch { return copy(initial); } }
function save() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function settingClass() { document.documentElement.dataset.theme = state.settings.theme; document.documentElement.dataset.font = state.settings.font; }
function songText(item) { return `${item.beats} / ${item.beats === 6 ? 8 : 4} - ${item.bpm} BPM`; }
function addToMaster(item) { if (!state.master.some(x => x.title.toLowerCase() === item.title.toLowerCase())) state.master.push(copy(item)); }
function render() {
  const hasSong = list().songs.length > 0, s = song() || { title: 'No song selected', bpm: 100, beats: 4, notes: '' }; settingClass(); $('nowPlaying').style.borderColor = list().color; $('songName').textContent = s.title; $('songDetails').textContent = hasSong ? songText(s) : 'Add a song from Master songs or + Add song'; $('bpm').value = s.bpm; $('bpmDisplay').value = s.bpm;
  $('soundSetting').checked = state.settings.sound; $('flashSetting').checked = state.settings.flash; $('soundType').value = state.settings.soundType; $('themeSetting').value = state.settings.theme; $('fontSetting').value = state.settings.font; $('setlistTitle').textContent = list().name;
  $('setlistPicker').replaceChildren(...state.setlists.map((entry, index) => new Option(entry.name, index, index === state.currentList, index === state.currentList)));
  $('play').disabled = !hasSong; $('slower').disabled = !hasSong; $('faster').disabled = !hasSong; $('bpm').disabled = !hasSong; $('play').setAttribute('aria-pressed', String(isPlaying)); $('playLabel').textContent = isPlaying ? 'Stop' : 'Start'; $('playIcon').textContent = isPlaying ? 'Stop' : 'Play'; $('beatText').textContent = hasSong ? (isPlaying ? `Beat ${beat + 1} of ${s.beats}` : 'Ready') : 'Build this set list';
  $('beatRow').replaceChildren(...Array.from({ length: s.beats }, (_, i) => { const dot = document.createElement('span'); dot.className = `beat${i === 0 ? ' accent' : ''}${isPlaying && i === beat ? ' active' : ''}`; return dot; }));
  $('setlist').replaceChildren(...list().songs.map((item, index) => { const row = document.createElement('li'), wrap = document.createElement('div'), select = document.createElement('button'), tools = document.createElement('div'); select.type = 'button'; select.className = `song${index === state.current ? ' active' : ''}`; select.innerHTML = '<span class="song-number"></span><span><span class="song-title"></span><span class="song-meta"></span><span class="song-notes"></span></span><span class="song-bpm"></span>'; select.querySelector('.song-number').textContent = index + 1; select.querySelector('.song-title').textContent = item.title; select.querySelector('.song-meta').textContent = `${item.beats} / ${item.beats === 6 ? 8 : 4}`; select.querySelector('.song-notes').textContent = item.notes || ''; select.querySelector('.song-bpm').textContent = item.bpm; select.addEventListener('click', () => { state.current = index; beat = 0; stop(); save(); render(); }); tools.className = 'song-tools'; [['Edit', () => openSong(index)], ['Up', () => moveSong(index, -1)], ['Down', () => moveSong(index, 1)]].forEach(([label, action]) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = label; b.disabled = (label === 'Up' && index === 0) || (label === 'Down' && index === list().songs.length - 1); b.addEventListener('click', action); tools.append(b); }); wrap.append(select, tools); row.append(wrap); return row; }));
}
function moveSong(index, direction) { const target = index + direction; if (target < 0 || target >= list().songs.length) return; [list().songs[index], list().songs[target]] = [list().songs[target], list().songs[index]]; if (state.current === index) state.current = target; else if (state.current === target) state.current = index; save(); render(); }
function audioContext() { audio ||= new (window.AudioContext || window.webkitAudioContext)(); return audio; }
function tone(freq, duration, type = 'sine', gainValue = .12) { const ctx = audioContext(), osc = ctx.createOscillator(), gain = ctx.createGain(); osc.type = type; osc.frequency.setValueAtTime(freq, ctx.currentTime); gain.gain.setValueAtTime(gainValue, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + duration); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + duration); }
function noise(duration, gainValue) { const ctx = audioContext(), buffer = ctx.createBuffer(1, ctx.sampleRate * duration, ctx.sampleRate), data = buffer.getChannelData(0); for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1; const source = ctx.createBufferSource(), gain = ctx.createGain(); source.buffer = buffer; gain.gain.setValueAtTime(gainValue, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + duration); source.connect(gain).connect(ctx.destination); source.start(); }
function playClick(accent) { if (!state.settings.sound) return; const boost = accent ? 1.22 : 1, type = state.settings.soundType; if (type === 'wood') tone(880 * boost, .07, 'square', .08); if (type === 'cowbell') { tone(560 * boost, .12, 'square', .055); tone(845 * boost, .12, 'square', .04); } if (type === 'clap') { noise(.06, .10); setTimeout(() => noise(.035, .05), 18); } if (type === 'rim') { tone(1800 * boost, .045, 'square', .06); noise(.03, .04); } if (type === 'kick') { const ctx = audioContext(), osc = ctx.createOscillator(), gain = ctx.createGain(); osc.frequency.setValueAtTime(145 * boost, ctx.currentTime); osc.frequency.exponentialRampToValueAtTime(48, ctx.currentTime + .12); gain.gain.setValueAtTime(.2, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .13); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .14); } }
function flash(accent) { if (!state.settings.flash) return; const el = $('flash'); el.className = `flash ${accent ? 'accent' : 'hit'}`; setTimeout(() => el.className = 'flash', 160); }
function tick() { if (!song()) return stop(); const accent = beat === 0; playClick(accent); flash(accent); render(); beat = (beat + 1) % song().beats; timer = setTimeout(tick, 60000 / song().bpm); }
function start() { if (!isPlaying && song()) { isPlaying = true; beat = 0; tick(); render(); } } function stop() { isPlaying = false; clearTimeout(timer); timer = null; render(); }
function changeSong(amount) { if (!list().songs.length) return; state.current = (state.current + amount + list().songs.length) % list().songs.length; beat = 0; save(); render(); }
function openSong(index) { editing = index; const s = index === null ? { title: '', bpm: 120, beats: 4, notes: '' } : list().songs[index]; $('dialogTitle').textContent = index === null ? 'Add song' : 'Edit song'; $('titleInput').value = s.title; $('tempoInput').value = s.bpm; $('signatureInput').value = s.beats; $('notesInput').value = s.notes; $('saveToLibrary').checked = true; $('deleteSong').hidden = index === null; $('songDialog').showModal(); }
function openSetlist() { $('setlistNameInput').value = list().name; $('setlistColorInput').value = list().color; $('deleteSetlist').disabled = state.setlists.length === 1; $('setlistDialog').showModal(); }
function openLibrary() { const holder = $('libraryList'); holder.replaceChildren(...state.master.map(item => { const row = document.createElement('div'), info = document.createElement('span'), button = document.createElement('button'); row.className = 'library-row'; info.textContent = `${item.title} - ${songText(item)}`; button.type = 'button'; button.textContent = 'Add'; button.addEventListener('click', () => { list().songs.push(copy(item)); save(); render(); }); row.append(info, button); return row; })); $('libraryDialog').showModal(); }
$('play').addEventListener('click', () => isPlaying ? stop() : start()); $('previousSong').addEventListener('click', () => changeSong(-1)); $('nextSong').addEventListener('click', () => changeSong(1));
$('slower').addEventListener('click', () => { if (!song()) return; song().bpm = Math.max(40, song().bpm - 1); save(); render(); }); $('faster').addEventListener('click', () => { if (!song()) return; song().bpm = Math.min(240, song().bpm + 1); save(); render(); }); $('bpm').addEventListener('input', e => { if (!song()) return; song().bpm = Number(e.target.value); save(); render(); });
$('addSong').addEventListener('click', () => openSong(null)); $('masterLibrary').addEventListener('click', openLibrary); $('editSetlist').addEventListener('click', openSetlist); $('newSetlist').addEventListener('click', () => { const name = prompt('Name this set list', 'New set list'); if (!name?.trim()) return; state.setlists.push({ name: name.trim(), color: '#8eaeff', songs: [] }); state.currentList = state.setlists.length - 1; state.current = 0; save(); render(); }); $('setlistPicker').addEventListener('change', e => { state.currentList = Number(e.target.value); state.current = 0; beat = 0; stop(); save(); render(); });
$('settingsButton').addEventListener('click', () => $('settingsDialog').showModal()); [['soundSetting','sound'],['flashSetting','flash']].forEach(([id,key]) => $(id).addEventListener('change', e => { state.settings[key] = e.target.checked; save(); })); [['soundType','soundType'],['themeSetting','theme'],['fontSetting','font']].forEach(([id,key]) => $(id).addEventListener('change', e => { state.settings[key] = e.target.value; save(); render(); }));
$('songForm').addEventListener('submit', e => { if (e.submitter?.value !== 'default') return; const item = { title: $('titleInput').value.trim(), bpm: Number($('tempoInput').value), beats: Number($('signatureInput').value), notes: $('notesInput').value.trim() }; if (!item.title) { e.preventDefault(); return; } if (editing === null) { list().songs.push(item); state.current = list().songs.length - 1; } else list().songs[editing] = item; if ($('saveToLibrary').checked) addToMaster(item); beat = 0; save(); render(); }); $('deleteSong').addEventListener('click', () => { list().songs.splice(editing, 1); state.current = Math.max(0, Math.min(state.current, list().songs.length - 1)); $('songDialog').close(); save(); render(); });
$('setlistForm').addEventListener('submit', e => { if (e.submitter?.value !== 'default') return; list().name = $('setlistNameInput').value.trim() || 'Untitled'; list().color = $('setlistColorInput').value; save(); render(); }); $('deleteSetlist').addEventListener('click', () => { if (state.setlists.length === 1) return; state.setlists.splice(state.currentList, 1); state.currentList = 0; state.current = 0; $('setlistDialog').close(); save(); render(); });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js'); render();
